import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import { schemaDocFromFa3cbe7Postgres } from '../scripts/fa3cbe7-postgres-schema-doc';
import { buildMysqlSchemaDoc, buildPostgresSchemaDoc } from '../src/introspect';
import { parseSchemaDoc } from '../src/schema-parse';
import {
  buildCheckEnumMap,
  buildDdl,
  buildNativeEnumMap,
  mergeEnumMaps,
  type SchemaColumnRow,
} from '../src/schema-enum';
import type { MysqlForeignKeyQueryRow, PgForeignKeyQueryRow } from '../src/schema-fk';
import type {
  MysqlColumnQueryRow,
  PgCheckQueryRow,
  PgColumnQueryRow,
  PgNativeEnumQueryRow,
} from '../src/introspect';
import {
  introspectionSqlSha256,
  loadIntrospectionSql,
} from '../scripts/introspection-sql';

function readJson<T>(file: string): T {
  return JSON.parse(readFileSync(file, 'utf8')) as T;
}

function readText(file: string): string {
  return readFileSync(file, 'utf8').replace(/\n$/, '');
}

const LOCALE_SCHEMA_DOC: Record<string, string> = {
  'C.UTF-8': 'schema-doc.C.txt',
  'en_US.UTF-8': 'schema-doc.en_US.txt',
  'zh_CN.UTF-8': 'schema-doc.zh_CN.txt',
  'sv_SE.UTF-8': 'schema-doc.sv_SE.txt',
};

function schemaDocFileForLcAll(lcAll: string | undefined): string {
  if (!lcAll || !Object.hasOwn(LOCALE_SCHEMA_DOC, lcAll)) {
    throw new Error(
      `LC_ALL ${JSON.stringify(lcAll ?? '')} has no committed schemaDoc literal`,
    );
  }
  return LOCALE_SCHEMA_DOC[lcAll];
}

function literalSchemaDoc(dir: string): string {
  return readText(path.join(dir, schemaDocFileForLcAll(process.env.LC_ALL)));
}

const pgDir = path.join('test', 'golden', 'sample-postgres');
const syntheticPgDir = path.join('test', 'golden', 'synthetic-postgres');
const mysqlDir = path.join('test', 'golden', 'synthetic-mysql');

describe('sample postgres golden', () => {
  const columns = readJson<PgColumnQueryRow[]>(path.join(pgDir, 'columns.json'));
  const nativeEnums = readJson<PgNativeEnumQueryRow[]>(path.join(pgDir, 'native-enums.json'));
  const checks = readJson<PgCheckQueryRow[]>(path.join(pgDir, 'checks.json'));
  const foreignKeys = readJson<PgForeignKeyQueryRow[]>(path.join(pgDir, 'foreign-keys.json'));
  const metadata = readJson<{
    capture: string;
    introspectionSqlSha256: Record<string, string>;
    tableCount: number;
  }>(path.join(pgDir, 'metadata.json'));

  it('was captured from the sample schema database', () => {
    assert.equal(metadata.capture, 'db-captured');
  });

  it('matches buildDdl with no foreign keys', () => {
    const typedRows: SchemaColumnRow[] = columns.map((row) => ({
      table_name: row.table_name,
      column_name: row.column_name,
      data_type: row.data_type,
      is_nullable: row.is_nullable,
    }));
    const schemaDoc = buildDdl(
      typedRows,
      mergeEnumMaps(buildNativeEnumMap(columns, nativeEnums), buildCheckEnumMap(checks)),
    );
    assert.equal(schemaDoc, readText(path.join(pgDir, 'schema-doc.txt')));
    assert.doesNotMatch(schemaDoc, /FOREIGN KEY/);
    assert.deepEqual(parseSchemaDoc(schemaDoc), readJson(path.join(pgDir, 'parsed-tables.json')));
  });

  it('matches frozen Postgres post-processing including foreign keys', () => {
    const built = buildPostgresSchemaDoc(columns, nativeEnums, checks, foreignKeys);
    assert.equal(built.schemaDoc, readText(path.join(pgDir, 'schema-doc-with-fks.txt')));
    assert.equal(built.tableCount, metadata.tableCount);
    assert.match(built.schemaDoc, /FOREIGN KEY/);
    assert.deepEqual(
      parseSchemaDoc(built.schemaDoc),
      readJson(path.join(pgDir, 'parsed-tables-with-fks.json')),
    );
  });

  it('records sha256 of each introspection SQL string', () => {
    assert.deepEqual(metadata.introspectionSqlSha256, introspectionSqlSha256(loadIntrospectionSql()));
  });
});

describe('synthetic postgres golden', () => {
  const columns = readJson<PgColumnQueryRow[]>(path.join(syntheticPgDir, 'columns.json'));
  const nativeEnums = readJson<PgNativeEnumQueryRow[]>(path.join(syntheticPgDir, 'native-enums.json'));
  const checks = readJson<PgCheckQueryRow[]>(path.join(syntheticPgDir, 'checks.json'));
  const foreignKeys = readJson<PgForeignKeyQueryRow[]>(path.join(syntheticPgDir, 'foreign-keys.json'));
  const metadata = readJson<{
    capture: string;
    schemaDocGeneratedBy: string;
    introspectionSqlSha256: Record<string, string>;
    tableCount: number;
  }>(path.join(syntheticPgDir, 'metadata.json'));

  it('was captured from a database and generated by the fa3cbe7 path', () => {
    assert.equal(metadata.capture, 'db-captured');
    assert.match(metadata.schemaDocGeneratedBy, /Not buildPostgresSchemaDoc/);
    assert.ok(nativeEnums.length > 0);
    assert.ok(checks.length > 0);
    assert.ok(foreignKeys.length > 0);
    const composer = readFileSync('scripts/fa3cbe7-postgres-schema-doc.ts', 'utf8');
    assert.match(composer, /test\/reference\/fa3cbe7\/schema-enum/);
    assert.match(composer, /test\/reference\/fa3cbe7\/schema-fk/);
    assert.doesNotMatch(composer, /from ['"]\.\.\/src\//);
  });

  it('rejects an empty LC_ALL instead of selecting the en_US literal', () => {
    assert.throws(() => schemaDocFileForLcAll(''), /no committed schemaDoc literal/);
    assert.throws(() => schemaDocFileForLcAll(undefined), /no committed schemaDoc literal/);
    assert.equal(Object.hasOwn(LOCALE_SCHEMA_DOC, ''), false);
  });

  it('matches the committed literal for this LC_ALL', () => {
    const original = schemaDocFromFa3cbe7Postgres(columns, nativeEnums, checks, foreignKeys);
    const built = buildPostgresSchemaDoc(columns, nativeEnums, checks, foreignKeys);
    const literal = literalSchemaDoc(syntheticPgDir);
    assert.equal(built.schemaDoc, original.schemaDoc);
    assert.equal(built.schemaDoc, literal);
    assert.equal(built.tableCount, original.tableCount);
    assert.equal(built.tableCount, metadata.tableCount);
    assert.equal(metadata.tableCount, 6);

    const enUs = readText(path.join(syntheticPgDir, 'schema-doc.en_US.txt'));
    const cLocale = readText(path.join(syntheticPgDir, 'schema-doc.C.txt'));
    const swedish = readText(path.join(syntheticPgDir, 'schema-doc.sv_SE.txt'));
    const chinese = readText(path.join(syntheticPgDir, 'schema-doc.zh_CN.txt'));
    assert.equal(enUs, readText(path.join(syntheticPgDir, 'schema-doc.txt')));
    assert.equal(cLocale, enUs);
    assert.equal(swedish, enUs);
    assert.notEqual(chinese, enUs);

    const schemaDoc = built.schemaDoc;
    assert.match(schemaDoc, /status_code character varying NOT NULL,/);
    assert.doesNotMatch(schemaDoc, /status_code[^\n]*enum:/);
    assert.match(schemaDoc, /CREATE TABLE Orders \(/);
    assert.match(
      schemaDoc,
      /CONSTRAINT Orders_region_id_fkey FOREIGN KEY \(region_id\) REFERENCES regions \(id\)/,
    );
    assert.match(
      schemaDoc,
      /CONSTRAINT fk_items_order_line FOREIGN KEY \(order_id, line_no\) REFERENCES OrderLines \(order_id, line_no\)/,
    );
    assert.match(schemaDoc, /CREATE TABLE order_status_view \(/);
    assert.doesNotMatch(schemaDoc, /CREATE VIEW/);
    assert.doesNotMatch(schemaDoc, /CREATE TABLE order_status_view \([\s\S]*shipped/);
    assert.match(schemaDoc, /CREATE TABLE 订单 \(/);

    const parsed = parseSchemaDoc(schemaDoc);
    assert.equal(
      parsed.find((table) => table.name === '订单'),
      undefined,
    );
    const orders = parsed.find((table) => table.name === 'Orders');
    assert.equal(
      orders?.columns.find((column) => column.name === 'status_code')?.enumValues,
      undefined,
    );
  });

  it('records sha256 of each introspection SQL string', () => {
    assert.deepEqual(metadata.introspectionSqlSha256, introspectionSqlSha256(loadIntrospectionSql()));
  });
});

describe('synthetic mysql golden', () => {
  const columns = readJson<MysqlColumnQueryRow[]>(path.join(mysqlDir, 'columns.json'));
  const foreignKeys = readJson<MysqlForeignKeyQueryRow[]>(path.join(mysqlDir, 'foreign-keys.json'));
  const metadata = readJson<{
    capture: string;
    introspectionSqlSha256: Record<string, string>;
    tableCount: number;
  }>(path.join(mysqlDir, 'metadata.json'));

  it('was captured from the synthetic database', () => {
    assert.equal(metadata.capture, 'db-captured');
  });

  it('matches the committed literal for this LC_ALL', () => {
    const built = buildMysqlSchemaDoc(columns, foreignKeys);
    const literal = literalSchemaDoc(mysqlDir);
    assert.equal(built.schemaDoc, literal);
    assert.equal(built.tableCount, metadata.tableCount);

    const enUs = readText(path.join(mysqlDir, 'schema-doc.en_US.txt'));
    const cLocale = readText(path.join(mysqlDir, 'schema-doc.C.txt'));
    const swedish = readText(path.join(mysqlDir, 'schema-doc.sv_SE.txt'));
    const chinese = readText(path.join(mysqlDir, 'schema-doc.zh_CN.txt'));
    assert.equal(enUs, readText(path.join(mysqlDir, 'schema-doc.txt')));
    assert.equal(cLocale, enUs);
    assert.equal(swedish, enUs);
    assert.notEqual(chinese, enUs);

    const schemaDoc = built.schemaDoc;
    const parsed = parseSchemaDoc(schemaDoc);

    assert.match(schemaDoc, /CREATE TABLE order_status_view \(/);
    assert.doesNotMatch(schemaDoc, /CREATE VIEW/);
    assert.ok(parsed.some((table) => table.name === 'order_status_view'));

    assert.match(schemaDoc, /CREATE TABLE 订单 \(/);
    assert.equal(
      parsed.find((table) => table.name === '订单'),
      undefined,
    );

    const orders = parsed.find((table) => table.name === 'Orders');
    assert.ok(orders);
    const channel = orders.columns.find((column) => column.name === 'channel');
    assert.equal(channel?.enumValues, undefined);

    assert.match(
      schemaDoc,
      /CONSTRAINT fk_items_order_line FOREIGN KEY \(order_id, line_no\) REFERENCES OrderLines \(order_id, line_no\)/,
    );
  });

  it('records sha256 of each introspection SQL string', () => {
    assert.deepEqual(metadata.introspectionSqlSha256, introspectionSqlSha256(loadIntrospectionSql()));
  });
});
